name: Run get_v2_3.py

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'  # You can specify another Python version here

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install chromedriver-autoinstaller  # In case chromedriver is needed for selenium

    # Step 4: Run the script
    - name: Run Python script
      run: |
        python scripts/get_v2_3.py

    # Step 5: Upload the result (optional, if you want to save the result as artifact)
    - name: Upload v2.txt
      uses: actions/upload-artifact@v2
      with:
        name: v2-file
        path: v2.txt
