name: Update IPTV

on:
  schedule:
    - cron: '0 2 * * *'   # 每天凌晨 2 点运行
  workflow_dispatch:       # 手动触发

permissions:
  contents: write          # 允许工作流写入仓库

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python scripts/import_sources.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add valid2.m3u
          git commit -m "Update valid2.m3u" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin HEAD:main
